# Generated by Django 5.0.6 on 2024-06-25 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Condominio',
            fields=[
                ('nome', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Condominio')),
            ],
            options={
                'verbose_name_plural': 'Condomini',
            },
        ),
    ]
