# Generated by Django 5.0.6 on 2024-08-05 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Condominio', '0002_interno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interno',
            old_name='numero',
            new_name='numero_interno',
        ),
        migrations.AddField(
            model_name='interno',
            name='palazzina',
            field=models.ForeignKey(default='Salgari', on_delete=django.db.models.deletion.CASCADE, to='Condominio.condominio'),
        ),
    ]
