# Generated by Django 5.0.6 on 2024-08-09 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Condominio', '0005_documentipalazzo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fornitore',
            fields=[
                ('nome', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('contratto', models.FileField(blank=True, default=None, upload_to='', verbose_name='Contratto')),
                ('indirizzo', models.CharField(max_length=200)),
                ('ragione_sociale', models.CharField(max_length=100)),
                ('partita_iva', models.CharField(max_length=100)),
                ('cf', models.CharField(max_length=100)),
                ('iban', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Fornitori',
            },
        ),
    ]
