# Generated by Django 5.0.6 on 2024-08-20 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Condominio', '0006_fornitore'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(verbose_name='Data')),
                ('tipologia', models.TextField(choices=[('Luce Palazzina', 'Luce Palazzina'), ('Scale Palazzina', 'Scale Palazzina'), ('Manutenzione Ordinaria', 'Manutenzione Ordinaria'), ('Manutenzione Ordinaria Comune', 'Manutenzione Ordinaria Comune'), ('Spese Generali', 'Spesa Generale'), ('Spesa Straordinaria', 'Spesa Straordinaria'), ('Spesa Straordinaria Comune', 'Spesa Straordinaria Comune'), ('Spese Diverse', 'Spese Diverse')], default='Spese Diverse', max_length=200, verbose_name='Tipologia')),
                ('descrizione', models.CharField(default=None, max_length=200)),
                ('assegnatario', models.TextField(verbose_name='Assegnatario')),
                ('importo', models.FloatField(default=0, verbose_name='Totale')),
                ('fornitore', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Condominio.fornitore')),
            ],
            options={
                'verbose_name_plural': 'Spese',
            },
        ),
    ]
