# Generated by Django 5.0.6 on 2024-08-26 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Condominio', '0008_notification_alter_spesa_fornitore_usernotification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interno',
            name='millesimi_edificio',
            field=models.FloatField(default=0, verbose_name='Millesimi Edificio'),
            preserve_default=False,
        ),
    ]
