# Generated by Django 5.0.6 on 2024-08-26 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Condominio', '0010_interno_numero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interno',
            name='numero',
        ),
        migrations.AlterField(
            model_name='interno',
            name='numero_interno',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Numero Interno'),
        ),
    ]
