# Generated by Django 5.0.6 on 2024-08-26 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Condominio', '0011_remove_interno_numero_alter_interno_numero_interno'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interno',
            options={'ordering': ['numero_interno'], 'verbose_name_plural': 'Interni'},
        ),
    ]
