# Generated by Django 5.0.6 on 2024-08-26 14:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Condominio', '0012_alter_interno_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spesa',
            name='assegnatario',
        ),
        migrations.AddField(
            model_name='spesa',
            name='assegnatario',
            field=models.ManyToManyField(related_name='Assegnatario', to=settings.AUTH_USER_MODEL),
        ),
    ]
