# Generated by Django 5.0.6 on 2024-08-29 09:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Condominio', '0015_alter_spesa_assegnatario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='spesa',
            name='assegnatario',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
