# Generated by Django 5.0.6 on 2024-08-29 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Condominio', '0016_alter_spesa_assegnatario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spesa',
            name='assegnatario',
            field=models.ManyToManyField(to='Condominio.interno'),
        ),
    ]
