# Generated by Django 5.0.6 on 2024-08-31 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Condominio', '0019_alter_spesa_assegnatario_alter_spesa_tipologia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spesa',
            name='tipologia',
            field=models.TextField(choices=[('Luce Palazzina', 'Luce Palazzina'), ('Scale Palazzina', 'Scale Palazzina'), ('Manutenzione Ordinaria', 'Manutenzione Ordinaria'), ('Manutenzione Ordinaria Comune', 'Manutenzione Ordinaria Comune'), ('Manutenzione Ordinaria Scala', 'Manutenzione Ordinaria Scala'), ('Spese Generali', 'Spesa Generale'), ('Spese Straordinarie', 'Spesa Straordinaria'), ('Spesa Straordinaria Edificio', 'Spesa Straordinaria Edificio'), ('Spesa Straordinaria Scale', 'Spesa Straordinaria Scale'), ('Spesa Straordinaria Antenne', 'Spesa Straordinaria Antenne'), ('Spese Diverse', 'Spese Diverse')], default='Spese Diverse', max_length=200, verbose_name='Tipologia'),
        ),
    ]
