# Generated by Django 5.1.1 on 2024-09-13 14:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Condominio', '0020_alter_spesa_tipologia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usernotification',
            name='notification',
        ),
        migrations.RemoveField(
            model_name='usernotification',
            name='user',
        ),
        migrations.RemoveField(
            model_name='interno',
            name='mappali',
        ),
        migrations.RemoveField(
            model_name='interno',
            name='millesimi_edificio',
        ),
        migrations.AlterField(
            model_name='interno',
            name='condomino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='interno',
            name='palazzina',
            field=models.ForeignKey(default='Salgari', on_delete=django.db.models.deletion.PROTECT, to='Condominio.condominio'),
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='UserNotification',
        ),
    ]
