# Generated by Django 5.1.1 on 2024-09-16 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Condominio', '0021_remove_usernotification_notification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentipalazzo',
            name='file_documento',
            field=models.FileField(blank=True, default=None, upload_to='documenti_palazzo/', verbose_name='Documento del Palazzo'),
        ),
        migrations.AlterField(
            model_name='lettera_convocazione',
            name='convocazione_documento',
            field=models.FileField(blank=True, default=None, upload_to='lettere/', verbose_name='Lettera di convocazione'),
        ),
        migrations.AlterField(
            model_name='verbale',
            name='documento',
            field=models.FileField(blank=True, default=None, upload_to='verbali/', verbose_name='Documento'),
        ),
        migrations.AlterField(
            model_name='verbale',
            name='lettera_accompagnatoria',
            field=models.FileField(blank=True, default=None, upload_to='lettereAccompagnatorie/', verbose_name='Lettera accompagnatoria'),
        ),
    ]
