# Generated by Django 5.1.2 on 2024-11-29 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Condominio', '0028_delete_rata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentipalazzo',
            name='file_documento',
            field=models.FileField(blank=True, default=None, upload_to='static/files', verbose_name='Documento del Palazzo'),
        ),
        migrations.AlterField(
            model_name='fornitore',
            name='contratto',
            field=models.FileField(blank=True, default=None, upload_to='static/files', verbose_name='Contratto'),
        ),
        migrations.AlterField(
            model_name='lettera_convocazione',
            name='convocazione_documento',
            field=models.FileField(blank=True, default=None, upload_to='static/files', verbose_name='Lettera di convocazione'),
        ),
        migrations.AlterField(
            model_name='verbale',
            name='documento',
            field=models.FileField(blank=True, default=None, upload_to='static/files', verbose_name='Documento'),
        ),
    ]
