# Generated by Django 5.1.2 on 2024-12-02 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Condominio', '0029_alter_documentipalazzo_file_documento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lettera_convocazione',
            name='convocazione_documento',
            field=models.FileField(blank=True, default=None, upload_to='media/', verbose_name='Lettera di convocazione'),
        ),
    ]
