# Generated by Django 5.1.3 on 2024-12-04 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Condominio', '0031_alter_documentipalazzo_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verbale',
            name='data',
            field=models.DateField(primary_key=True, serialize=False, verbose_name='Data'),
        ),
    ]
