# Generated by Django 5.1.3 on 2024-12-04 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Condominio', '0032_alter_verbale_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentipalazzo',
            name='data',
            field=models.DateTimeField(primary_key=True, serialize=False, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='lettera_convocazione',
            name='data',
            field=models.DateTimeField(primary_key=True, serialize=False, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='spesa',
            name='data',
            field=models.DateTimeField(verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='verbale',
            name='data',
            field=models.DateTimeField(primary_key=True, serialize=False, verbose_name='Data'),
        ),
    ]
