# Generated by Django 5.1.3 on 2024-12-04 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Condominio', '0033_alter_documentipalazzo_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lettera_convocazione',
            name='data',
            field=models.DateField(primary_key=True, serialize=False, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='spesa',
            name='data',
            field=models.DateField(verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='verbale',
            name='data',
            field=models.DateField(primary_key=True, serialize=False, verbose_name='Data'),
        ),
    ]
