# Generated by Django 5.1.3 on 2024-12-06 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Condominio', '0034_alter_lettera_convocazione_data_alter_spesa_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lettera_convocazione',
            name='data',
            field=models.DateTimeField(primary_key=True, serialize=False, verbose_name='Data'),
        ),
    ]
