# Generated by Django 5.1.3 on 2024-12-06 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Condominio', '0035_alter_lettera_convocazione_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lettera_convocazione',
            name='data',
            field=models.DateField(primary_key=True, serialize=False, verbose_name='Data'),
        ),
    ]
