# Generated by Django 5.1.3 on 2024-12-06 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Condominio', '0036_alter_lettera_convocazione_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentipalazzo',
            name='file_documento',
            field=models.FileField(blank=True, default=None, upload_to='files/', verbose_name='Documento del Palazzo'),
        ),
        migrations.AlterField(
            model_name='fornitore',
            name='contratto',
            field=models.FileField(blank=True, default=None, upload_to='files/', verbose_name='Contratto'),
        ),
        migrations.AlterField(
            model_name='lettera_convocazione',
            name='convocazione_documento',
            field=models.FileField(blank=True, default=None, upload_to='files/', verbose_name='Lettera di convocazione'),
        ),
        migrations.AlterField(
            model_name='verbale',
            name='documento',
            field=models.FileField(blank=True, default=None, upload_to='files/', verbose_name='Documento'),
        ),
        migrations.AlterField(
            model_name='verbale',
            name='lettera_accompagnatoria',
            field=models.FileField(blank=True, default=None, upload_to='files/', verbose_name='Lettera accompagnatoria'),
        ),
    ]
