# Generated by Django 5.1.3 on 2024-12-27 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Condominio', '0037_alter_documentipalazzo_file_documento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(default='Nuova Notifica', max_length=200, verbose_name='Titolo')),
                ('descrizione', models.CharField(default='Vai a vedere in Bacheca', max_length=200, verbose_name='Descrizione')),
                ('data', models.DateField(verbose_name='Data')),
            ],
            options={
                'verbose_name_plural': 'Notifica',
            },
        ),
    ]
