# Generated by Django 5.1.3 on 2024-12-31 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Condominio', '0038_notifica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornitore',
            name='indirizzo',
            field=models.CharField(blank=True, default='non dichiarato', max_length=200),
        ),
    ]
